代码熟练度练习2/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using 代码熟练度练习2.Models;

namespace 代码熟练度练习2.Controllers
{
    public class UserInfoController : Controller
    {
        //JHcoTextDemoEntities db = new JHcoTextDemoEntities();
        // GET: UserInfo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllUsers()
        {
            var temp = DbContentFactory.GetCurrentDbContent().UserInfo.Where(u => true).Select(u=> new { u.Id, u.UName, u.ShowName, u.SubTime, u.ModifedOn, u.Pwd, u.Remark }); ;
            var total = DbContentFactory.GetCurrentDbContent().UserInfo.Count();
            var data = new { total = total, rows = temp.ToList() };//按照上面的table格式传送数据

            return Json(data, JsonRequestBehavior.AllowGet);//JsonRequestBehavior.AllowGet允许客户端传的get请求
        }

        public ActionResult Add(UserInfo ui)
        {
            ui.ModifedOn = DateTime.Now;
            ui.SubTime = DateTime.Now;
            ui.DelFlag = (short)Models.Enum.DelFlagEnum.Normal;
            DbContentFactory.GetCurrentDbContent().UserInfo.Add(ui);
            DbContentFactory.GetCurrentDbContent().SaveChanges();
            return Content("OK");
        }

        public ActionResult Edit(int id)
        {
            ViewData.Model= DbContentFactory.GetCurrentDbContent().UserInfo.Where(u => u.Id == id).FirstOrDefault();
            return View();
        }
        [HttpPost]
        public ActionResult Edit(UserInfo ui)
        {
            DbContentFactory.GetCurrentDbContent().Entry(ui).State = System.Data.Entity.EntityState.Modified;
            DbContentFactory.GetCurrentDbContent().SaveChanges();
            return Content("OK");
        }

        public ActionResult Delete(string ids)
        {
            if (ids == null)
            {
                return Content("请选着要删除的项");
            }
            //把字符串分成数组
            string[] strId = ids.Split(',');

            List<int> lids = new List<int>();
            foreach (var id in strId)
            {
                lids.Add(int.Parse(id));
            }

            foreach (var id in lids)
            {
                var user=DbContentFactory.GetCurrentDbContent().UserInfo.Find(id);
                DbContentFactory.GetCurrentDbContent().UserInfo.Remove(user);

            }
            DbContentFactory.GetCurrentDbContent().SaveChanges();
            return Content("OK");
        }

        public ActionResult SetRole(int id)
        {
            var delFlag = (short)Models.Enum.DelFlagEnum.Normal;
            //查询给哪个用户添加角色
            var users=DbContentFactory.GetCurrentDbContent().UserInfo.Find(id);
            ViewBag.user = users;
            //查询出所有的角色
            ViewData.Model=DbContentFactory.GetCurrentDbContent().RoleInfo.Where(r => r.DelFlag == delFlag);

            //查询当前用户拥有的角色
            ViewBag.AllRole = (from u in users.RoleInfo
                        select u.Id).ToList();

            return View();
        }

        public ActionResult ProcessSetRole(int UId)
        {
            //第一：给谁设置角色
            int userId = UId;
            //第一：所有打上勾的角色
            List<int> lids = new List<int>();
            foreach (var item in Request.Form.AllKeys)//遍历表单的所有的key
            {
                if (item.Contains("ckb_"))
                {
                    var id= int.Parse(item.Replace("ckb_", ""));
                    lids.Add(id);
                }
            }
            //查询当前用户
            var user=DbContentFactory.GetCurrentDbContent().UserInfo.Find(userId);
            //清除当前用户的所有角色
            user.RoleInfo.Clear();

            //查询当前的角色
            foreach (var rid in lids)
            {
                var ruser=DbContentFactory.GetCurrentDbContent().RoleInfo.Find(rid);
                user.RoleInfo.Add(ruser);
            }
            DbContentFactory.GetCurrentDbContent().SaveChanges();
            return Content("OK");
        }
        //TODO:测试页面的Model类型
        public ActionResult Edit1(int id)
        {
            ViewData.Model = DbContentFactory.GetCurrentDbContent().UserInfo.Where(u => u.Id == id).FirstOrDefault();
            return View();
        }
    }
}

代码熟练度练习2/Views/UserInfo/Edit.cshtml
@model 代码熟练度练习2.UserInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        function formSubmit() {
            $('form').submit();
        }

        function afterEdit(date)
        {
            if (date == "OK") {
                window.parent.window.EditFormClose();
            } else {
                alert("修改失败 ");
            }
        }
    </script>
</head>
<body>
    @using (Ajax.BeginForm(new AjaxOptions() { OnSuccess="afterEdit"}))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>用户信息修改</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.UName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Pwd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Pwd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Pwd, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ShowName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ShowName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ShowName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DelFlag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DelFlag, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DelFlag, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ModifedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModifedOn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ModifedOn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SubTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SubTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SubTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

代码熟练度练习2/Views/UserInfo/Edit1.cshtml
@model 代码熟练度练习2.UserInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit1</title>
</head>
<body>
    <div> 
        <input type="text" value="@Model.UName"/>
    </div>
</body>
</html>

代码熟练度练习2/Views/UserInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Content/jqueryeasyui/jquery-3.0.0.min.js"></script>
    <script src="~/Content/jqueryeasyui/jquery.easyui.min.js"></script>
    <link href="~/Content/jqueryeasyui/themes/icon.css" rel="stylesheet" />
    <script src="~/Content/jqueryeasyui/locale/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <link href="~/Content/jqueryeasyui/themes/default/easyui.css" rel="stylesheet" />
    <script src="~/Scripts/datapattern.js"></script>
    <script type="text/javascript">
        $(function () {
            initTable();
            $('#divAddId').css('display', 'none');
            $('#divEditId').css('display', 'none');
        });

        function initTable() {
            $('#dTabId').datagrid({
                url: '/UserInfo/GetAllUsers',//发送请求时会同时发送2个参数rows:一页有多少条，page：请求当前页码
                title: '用户信息列表',
                width: 700,
                height: 400,
                fitColumns: true,
                idField: 'Id',
                loadMsg: '正在加载用户的信息...',
                pagination: true,
                singleSelect: false,
                pageSize: 5,
                pageNumber: 1,
                pageList: [5, 10, 20],
                columns: [[
                    //{ u.Id,u.UName,u.ShowName,u.SubTime,u.ModifedOn,u.Pwd,u.Remark}
                { field: 'ck', checkbox: true, align: 'left', width: 50 },
                { field: 'Id', title: '用户编号', width: 80 },
                { field: 'UName', title: '用户名', width: 120 },
                { field: 'Pwd', title: '密码', width: 120 },
                { field: 'Remark', title: '备注', width: 120 },
                //datapattern日期插件
                {
                    field: 'SubTime', title: '提交时间', width: 120, align: 'left',
                    formatter: function (value, row, index) {
                        return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-M-d h:m:s.S");
                    }
                },
                {
                    //field必须是后台返回的列必须得有这个属性才行
                    field: 'ModifedOn', title: '操作', width: 100, formatter: function (value, row, index) {
                        var str = "";
                        //在表格加载完成之后加载删除修改的事件
                        str += "<a href='javascript:void(0)' class='editLine' uid='" + row.Id + "'>修改</a> &nbsp;&nbsp;";
                        str += "<a href='javascript:void(0)' class='deleteLine' uid='" + row.Id + "'>删除</a>";
                        return str;
                    }
                }
                ]],
                toolbar: [{
                    id: 'btnDownShelf',
                    text: '添加用户',
                    iconCls: 'icon-add',
                    handler: function () {
                        //alert("ddddd");
                        //点击添加按钮弹出一个添加的对话框
                        addClickEvent();

                    }
                }, {
                    id: 'btnEdit',
                    text: '修改用户',
                    iconCls: 'icon-edit',
                    handler: function () {
                        //拿到当前选中的行
                        var selectRows = $('#dTabId').datagrid('getSelections');//调用对应表格下的getSelections方法(选中的行)
                        if (selectRows.length != 1)
                        {
                            $.messager.alert("错误提示", "请选着一条数据！", "question");
                            return;
                        }
                        EditClickEvent(selectRows[0].Id);
                    }
                }, {
                    id: 'btnEdit',
                    text: '删除用户用户',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        DeleteClickExent();
                        //拿到当前选中的行
                        //var selectRows = $('#dTabId').datagrid('getSelections');//调用对应表格下的getSelections方法(选中的行)
                        //if (selectRows.length == 0) {
                        //    $.messager.alert("错误提示", "请选着一条数据！", "question");
                        //    return;
                        //}
                        //EditClickEvent(selectRows[0].Id);
                    }
                }, {
                    id: 'btnEdit',
                    text: '给用户设置角色',
                    iconCls: 'icon-redo',
                    handler: function () {
                        //拿到当前选中的行
                        setRole();
                    }
                }],
                onHeaderContextMenu: function (e, field) {

                },//页面加载完成后给初始化的表格绑定点击修改事件
                onLoadSuccess: function () {
                    $('.editLine').click(function () {
                        var selectRows = $('#dTabId').datagrid('getSelections');//调用对应表格下的getSelections方法(选中的行)
                        if (selectRows.length != 1) {
                            $.messager.alert("错误提示", "请选着一条数据！", "question");
                            return;
                        }
                        var id = $(this).attr('uid');
                        EditClickEvent(id);
                    });
                }
            });
        }

        //给用户设置角色
        function setRole() {
            //拿到当前选中的行
            var selectRows = $('#dTabId').datagrid('getSelections');//调用对应表格下的getSelections方法(选中的行)
            if (selectRows.length <= 0) {
                $.messager.alert("错误提示", "请选着一条数据！", "question");
                return;
            }

            $('#RoleFram').attr("src", "/UserInfo/SetRole/" + selectRows[0].Id);
            $('#divRoleId').dialog({
                title: "设置角色",
                modl: true,
                width: 400,
                height: 400,
                minimizable: true,
                maximizable: true,
                resizable: true,
                buttons: [{
                    id: 'btnOk',
                    text: '保存',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //alert("ddddd");
                        //父容器控制子容器提交表单
                        $('#RoleFram')[0].contentWindow.formSubmit();
                    }
                }, {
                    id: 'btnCancel',
                    text: '取消',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        //alert("ccccc");
                        $("#divRoleId").dialog("close");
                    }
                }]
            });
        }

        //子页面关闭父页面窗体
        function afterSetRole() {
            $("#divRoleId").dialog("close");
            //刷新页面
            initTable();
        }

        //删除方法
        function DeleteClickExent() {
            //拿到当前选中的行
            var selectRows = $('#dTabId').datagrid('getSelections');//调用对应表格下的getSelections方法(选中的行)
            if (selectRows.length <=0) {
                $.messager.alert("错误提示", "请选着一条数据！", "question");
                return;
            }

            var ids = "";
            //遍历选中行
            for (var key in selectRows) {
                ids = ids + selectRows[key].Id+",";
            }
            ids = ids.substr(0, ids.length - 1);//去掉,号

            //alert(ids);
            $.post("/UserInfo/Delete", { ids: ids }, function (date) {
                if (date == "OK") {
                    initTable();
                    //解决EasyUi中的DataGrid删除一条记录后, 被删除的数据仍处于被选中状态(需要在成功清除 $("#tt").datagrid('clearSelections');)
                    $("#dTabId").datagrid('clearSelections');
                } else {
                    $.messager.alert("提示消息", date, "error");
                }
            });
        }
        //修改方法
        function EditClickEvent(id) {
            $('#editFram').attr('src', '/UserInfo/Edit/' + id);
            $('#divEditId').css('display', 'block');
            $('#divEditId').dialog({
                title: "修改用户",
                modl: true,
                width: 400,
                height: 400,
                minimizable: true,
                maximizable: true,
                resizable: true,
                buttons: [{
                    id: 'btnOk',
                    text: '保存',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //alert("ddddd");
                        //父容器控制子容器提交表单
                        $('#editFram')[0].contentWindow.formSubmit();
                    }
                }, {
                    id: 'btnCancel',
                    text: '取消',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        //alert("ccccc");
                        $("#divEditId").dialog("close");
                    }
                }]
            });
        }

        //子页面关闭父页面窗体
        function EditFormClose()
        {
            $("#divEditId").dialog("close");
            //刷新页面
            initTable();
        }

        //添加方法
        function addClickEvent()
        {
            $('#divAddId').css('display', 'block');
            $('#divAddId').dialog({
                title: "添加用户",
                modl: true,
                width: 400,
                height: 400,
                minimizable: true,
                maximizable: true,
                resizable: true,
                buttons: [{
                    id: 'btnOk',
                    text: '添加',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //alert("ddddd");
                        //把表单提交后台
                        subAddForm();
                    }
                }, {
                    id: 'btnCancel',
                    text: '取消',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        //alert("ccccc");
                        $("#divAddId").dialog("close");
                    }
                }]
            });
        }

        //表单提交后台
        function subAddForm() {
            $('#divAddId form').submit();
        }
        //返回的消息
        function afterAdd(data) {
            if (data == "OK") {
                //关闭对话框刷新表格
                $("#divAddId").dialog("close");
                initTable();
            } else {
                alert("添加失败");
            }
        }
    </script>
</head>
<body>
    <div id="dTabId"> 
    </div>
    @*添加列表-----------------------------------------------------------------*@
    <div id="divAddId">
        @using (Ajax.BeginForm("Add", "UserInfo", new AjaxOptions() { OnSuccess = "afterAdd" }))
        {
            <table>
                @*{ u.Id,u.UserName,u.ShowName,u.SubTime,u.ModifedOn,u.Password,u.Remark}*@
                <tr>
                    <td>用户名：</td>
                    <td><input type="text" name="UName" /></td>
                </tr>
                <tr>
                    <td>密码：</td>
                    <td><input type="password" name="Pwd" /></td>
                </tr>
                <tr>
                    <td>备注：</td>
                    <td><input type="text" name="Remark" /></td>
                </tr>
                <tr>
                    <td>昵称：</td>
                    <td><input type="text" name="ShowName" /></td>
                </tr>
            </table>
        }
    </div>
    @*修改列表-----------------------------------------------------------------*@
    <div id="divEditId">
        <iframe id="editFram" src="javascript:void(0)" frameborder="0" width="100%" height="100%"></iframe>
    </div>
    @*设置角色-----------------------------------------------------------------*@
    <div id="divRoleId">
        <iframe id="RoleFram" src="javascript:void(0)" frameborder="0" width="100%" height="100%"></iframe>
    </div>
</body>
</html>

代码熟练度练习2/Views/UserInfo/SetRole.cshtml
@*@model 代码熟练度练习2.RoleInfo*@
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetRole</title>
    <script src="~/Content/jqueryeasyui/jquery-3.0.0.min.js"></script>
    <script src="~/Content/jqueryeasyui/jquery.easyui.min.js"></script>
    <link href="~/Content/jqueryeasyui/themes/icon.css" rel="stylesheet" />
    <script src="~/Content/jqueryeasyui/locale/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <link href="~/Content/jqueryeasyui/themes/default/easyui.css" rel="stylesheet" />
    <script type="text/javascript">
        function formSubmit() {
            $('form').submit();
        }

        function afterSetRole(data) {
            if (data == "OK") {
                window.parent.window.afterSetRole();//调用父容器的方法
            } else {
                alert("失败了");
            }
        }
    </script>
</head>
<body>
    @{UserInfo ui = ViewBag.user;
    }
    <h3>给当前用户：@ui.UName 设置角色</h3>
    @{
        //获取当前用户的角色
        List<int> lid = ViewBag.AllRole;

        using (Ajax.BeginForm("ProcessSetRole", "UserInfo", new AjaxOptions() { OnSuccess = "afterSetRole" }))
        {
            <input type="hidden" name="UId" value="@ui.Id" />
            int i = 0;
            foreach (var roleinfo in Model)
            {
                string str = "ckb_" + roleinfo.Id;

                if (i % 2 == 0 && i != 0)
                {
                    <hr />
                }

                if (lid.Contains(roleinfo.Id))
                {

                    <input type="checkbox" checked="checked" value="@str" name="@str" id="@str" />
                }
                else
                {
                    <input type="checkbox" value="@str" name="@str" id="@str" />
                }

                <label for="@str">@roleinfo.RoleName</label>

                i++;
            }
        }
    }}
    <div> 
    </div>
</body>
</html>