代码熟练度练习2/Controllers/RoleInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using 代码熟练度练习2.Models;

namespace 代码熟练度练习2.Controllers
{
    public class RoleInfoController : Controller
    {
        short delflgNormal = (short)Models.Enum.DelFlagEnum.Normal;
        // GET: RoleInfo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllUsers()
        {
            var temp=DbContentFactory.GetCurrentDbContent().RoleInfo.Where(r => true).Select(r=>new { r.Id, r.RoleName, r.Remark, r.SubTime, r.ModifedOn, r.DelFlag });
            var data = new { total = temp.Count(), rows = temp.ToList() };//按照上面的table格式传送数据

            return Json(data, JsonRequestBehavior.AllowGet);//JsonRequestBehavior.AllowGet允许客户端传的get请求
        }

        public ActionResult Add(RoleInfo ri)
        {
            ri.DelFlag = delflgNormal;
            ri.ModifedOn = DateTime.Now;
            ri.SubTime = DateTime.Now;
            DbContentFactory.GetCurrentDbContent().RoleInfo.Add(ri);
            DbContentFactory.GetCurrentDbContent().SaveChanges();
            return Content("OK");
        }

        public ActionResult showedit(int id)
        {
            var temp = DbContentFactory.GetCurrentDbContent().RoleInfo.Where(r => r.Id == id).Select(r=>new { r.RoleName,r.Remark,r.Id}).FirstOrDefault();
            
            return Json(temp, JsonRequestBehavior.AllowGet);
        }

        public ActionResult edit(RoleInfo ri)
        {
            ri.DelFlag = delflgNormal;
            ri.ModifedOn = DateTime.Now;
            ri.SubTime = DateTime.Now;
            DbContentFactory.GetCurrentDbContent().Entry(ri).State = System.Data.Entity.EntityState.Modified;
            DbContentFactory.GetCurrentDbContent().SaveChanges();

            return Content("OK");
        }

        public ActionResult Delete(string ids)
        {
            if (ids == null)
            {
                return Content("请选着要删除的对象");
            }
            string[] sids= ids.Split(',');
            List<int> lid = new List<int>();

            foreach (var sid in sids)
            {
                lid.Add(int.Parse(sid));
            }
            foreach (var id in lid)
            {
                var temp=DbContentFactory.GetCurrentDbContent().RoleInfo.Find(id);
                DbContentFactory.GetCurrentDbContent().RoleInfo.Remove(temp);
            }
            DbContentFactory.GetCurrentDbContent().SaveChanges();

            return Content("OK");
        }
    }
}

代码熟练度练习2/Views/RoleInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Content/jqueryeasyui/jquery-3.0.0.min.js"></script>
    <script src="~/Content/jqueryeasyui/jquery.easyui.min.js"></script>
    <link href="~/Content/jqueryeasyui/themes/icon.css" rel="stylesheet" />
    <script src="~/Content/jqueryeasyui/locale/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <link href="~/Content/jqueryeasyui/themes/default/easyui.css" rel="stylesheet" />
    <script src="~/Scripts/datapattern.js"></script>
    <script type="text/javascript">
        $(function () {
            initTable();
            $('#addRoleId').css("display", "none");
            $('#editRoleId').css("display", "none");
        });
        function initTable() {
            $('#dTabId').datagrid({
                url: '/RoleInfo/GetAllUsers',//发送请求时会同时发送2个参数rows:一页有多少条，page：请求当前页码
                title: '角色信息列表',
                width: 700,
                height: 400,
                fitColumns: true,
                idField: 'Id',
                loadMsg: '正在加载角色的信息...',
                pagination: true,
                singleSelect: false,
                pageSize: 5,
                pageNumber: 1,
                pageList: [5, 10, 20],
                columns: [[
                    //a.Id, a.RoleName, a.Remark, a.SubTime, a.ModifedOn, a.DelFlag
                { field: 'ck', checkbox: true, align: 'left', width: 50 },
                { field: 'Id', title: '角色编号', width: 100 },
                { field: 'RoleName', title: '角色名', width: 120 },
                { field: 'Remark', title: '备注', width: 120 },
                //datapattern日期插件
                {
                    field: 'SubTime', title: '提交时间', width: 120, align: 'left',
                    formatter: function (value, row, index) {
                        return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-M-d h:m:s.S");
                    }
                },
                {
                    //field必须是后台返回的列必须得有这个属性才行
                    field: 'ModifedOn', title: '操作', width: 100, formatter: function (value, row, index) {
                        var str = "";
                        //在表格加载完成之后加载删除修改的事件
                        str += "<a href='javascript:void(0)' class='editLine' uid='" + row.Id + "'>修改</a> &nbsp;&nbsp;";
                        str += "<a href='javascript:void(0)' class='deleteLine' uid='" + row.Id + "'>删除</a>";
                        return str;
                    }
                }
                ]],
                toolbar: [{
                    id: 'btnDownShelf',
                    text: '添加角色',
                    iconCls: 'icon-add',
                    handler: function () {
                        //alert("ddddd");
                        //点击添加按钮弹出一个添加的对话框
                        addClickEvent();

                    }
                }, {
                    id: 'btnEdit',
                    text: '修改角色',
                    iconCls: 'icon-edit',
                    handler: function () {
                        //拿到当前选中的行
                        var selectRows = $('#dTabId').datagrid('getSelections');//调用对应表格下的getSelections方法(选中的行)
                        if (selectRows.length != 1) {
                            $.messager.alert("错误提示", "请选着一条数据！", "question");
                            return;
                        }
                        EditClickEvent(selectRows[0].Id);
                    }
                }, {
                    id: 'btnEdit',
                    text: '删除角色',
                    iconCls: 'icon-cancel',
                    handler: function () {
                        DeleteClickExent();
                        //拿到当前选中的行
                        //var selectRows = $('#dTabId').datagrid('getSelections');//调用对应表格下的getSelections方法(选中的行)
                        //if (selectRows.length == 0) {
                        //    $.messager.alert("错误提示", "请选着一条数据！", "question");
                        //    return;
                        //}
                        //EditClickEvent(selectRows[0].Id);
                    }
                }],
                onHeaderContextMenu: function (e, field) {

                },//页面加载完成后给初始化的表格绑定点击修改事件
                onLoadSuccess: function () {
                    $('.editLine').click(function () {
                        var selectRows = $('#dTabId').datagrid('getSelections');//调用对应表格下的getSelections方法(选中的行)
                        if (selectRows.length != 1) {
                            $.messager.alert("错误提示", "请选着一条数据！", "question");
                            return;
                        }
                        var id = $(this).attr('uid');
                        EditClickEvent(id);
                    });
                }
            });
        }
        //删除角色
        function DeleteClickExent() {
            var selectRows = $('#dTabId').datagrid('getSelections');//调用对应表格下的getSelections方法(选中的行)
            if (selectRows.length <= 0) {
                $.messager.alert("错误提示", "请选着一条数据！", "question");
                return;
            }

            var ids = "";
            for (var key in selectRows) {
                ids = ids + selectRows[key].Id+",";
            }

            ids = ids.substr(0, ids.length - 1);//去掉,号

            $.post("/RoleInfo/Delete", { ids: ids }, function (date) {
                if (date == "OK")
                {
                    initTable();
                    //解决EasyUi中的DataGrid删除一条记录后, 被删除的数据仍处于被选中状态(需要在成功清除 $("#tt").datagrid('clearSelections');)
                    $("#dTabId").datagrid('clearSelections');
                }else
                {
                    $.messager.alert("提示消息", date, "error");
                }
            });
        }

            //修改角色
            function EditClickEvent(id) {
                $.getJSON("/RoleInfo/showedit", { id: id }, function (date) {
                    $('#ptnId').val(date.Id);
                    $('#ptnName').val(date.RoleName);
                    $('#ptnRemk').val(date.Remark);

                });
                $('#editRoleId').css("display", "block");

                $('#editRoleId').dialog({
                    title: "添加角色",
                    modl: true,
                    width: 400,
                    height: 400,
                    minimizable: true,
                    maximizable: true,
                    resizable: true,
                    buttons: [{
                        id: 'btnOk',
                        text: '添加',
                        iconCls: 'icon-ok',
                        handler: function () {
                            //alert("ddddd");
                            //把表单提交后台
                            subEditForm();
                        }
                    }, {
                        id: 'btnCancel',
                        text: '取消',
                        iconCls: 'icon-cancel',
                        handler: function () {
                            //alert("ccccc");

                            $("#editRoleId").dialog("close");
                        }
                    }]
                });
            }
            //提交修改表单
            function subEditForm() {
                $('#editRoleId form').submit();
            }

            //执行回调方法
            function afterEdit(date) {
                if (date == "OK") {
                    $("#editRoleId").dialog("close");
                    initTable();
                } else {
                    alert(date);
                }
            }
            //添加角色
            function addClickEvent() {
                $('#addRoleId').css("display", "block");
                $('#addRoleId').dialog({
                    title: "修改角色",
                    modl: true,
                    width: 400,
                    height: 400,
                    minimizable: true,
                    maximizable: true,
                    resizable: true,
                    buttons: [{
                        id: 'btnOk',
                        text: '保存',
                        iconCls: 'icon-ok',
                        handler: function () {
                            //alert("ddddd");
                            //把表单提交后台
                            subAddForm();
                        }
                    }, {
                        id: 'btnCancel',
                        text: '取消',
                        iconCls: 'icon-cancel',
                        handler: function () {
                            //alert("ccccc");
                            $("#addRoleId").dialog("close");
                        }
                    }]
                });
            }
            //提交表单
            function subAddForm() {
                $('#addRoleId form').submit();
            }

            //执行回调方法
            function afterCreat(date) {
                if (date == "OK") {
                    $("#addRoleId").dialog("close");
                    initTable();
                } else {
                    alert(date);
                }
            }
    </script>

</head>
<body>
    <div id="dTabId"> 
    </div>
    @*添加角色--------------------------------------------------------------*@
    <div id="addRoleId">
        @using (Ajax.BeginForm("Add", "RoleInfo", new AjaxOptions() { OnSuccess = "afterCreat" }))
        {

            <table>
                @*a.Id, a.RoleName, a.Remark, a.SubTime, a.ModifedOn, a.DelFlag*@
                <tr>
                    <td>角色名：</td>
                    <td><input type="text" name="RoleName" /></td>
                </tr>
                <tr>
                    <td>备注：</td>
                    <td><input type="text" name="Remark" /></td>
                </tr>

            </table>
        }
        
    </div>
    @*修改界面--------------------------------------------------------------*@
    <div id="editRoleId">
        @using (Ajax.BeginForm("edit", "RoleInfo", new AjaxOptions() { OnSuccess = "afterEdit" }))
        {
            <input id="ptnId" type="hidden" name="Id" />
            <table>
                @*a.Id, a.RoleName, a.Remark, a.SubTime, a.ModifedOn, a.DelFlag*@
                <tr>
                    <td>角色名：</td>
                    <td><input id="ptnName" type="text" name="RoleName" /></td>
                </tr>
                <tr>
                    <td>备注：</td>
                    <td><input id="ptnRemk" type="text" name="Remark" /></td>
                </tr>

            </table>
        }
    </div>
</body>
</html>